# Generated by Django 3.2.6 on 2022-08-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_store_store_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_admin',
            new_name='user',
        ),
    ]
